# Generated by Django 5.1.7 on 2025-04-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0002_alter_document_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmit',
            name='is_score_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentsubmit',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
