# Generated by Django 5.1.7 on 2025-04-12 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0003_assignmentsubmit_is_score_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=3000)),
                ('publication_date', models.DateTimeField(auto_now=True)),
                ('modification_date', models.DateTimeField(default=None, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_app.user')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_app.group')),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_app.announcement')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_app.document')),
            ],
        ),
    ]
