# Generated by Django 5.1.7 on 2025-04-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0005_alter_announcement_publication_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
