# Generated by Django 5.1.1 on 2024-12-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('author_uid', models.IntegerField()),
                ('identifier', models.CharField(max_length=20, unique=True)),
                ('mime_type', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now=True)),
                ('data', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('token', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
