# Generated by Django 5.1.4 on 2025-01-08 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docu_rest_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='created',
            new_name='created_at',
        ),
    ]
