# Generated by Django 5.1.1 on 2024-12-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu_rest_app', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='identifier',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
