# Generated by Django 5.1.1 on 2024-12-15 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu_rest_app', '0003_document_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='document',
            name='mime_type',
            field=models.CharField(default=datetime.datetime(2024, 12, 15, 15, 43, 56, 437817, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
    ]
