# Generated by Django 5.1.1 on 2024-12-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu_rest_app', '0004_document_created_document_mime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='testFile', max_length=500),
            preserve_default=False,
        ),
    ]
