# Generated by Django 5.1.1 on 2024-11-20 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EPDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EPGroup',
            fields=[
                ('tag', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EPTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('instructions', models.CharField(max_length=2000)),
                ('due_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EPUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EPClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7)),
                ('archived', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduplatform_rest_app.epgroup')),
            ],
        ),
        migrations.CreateModel(
            name='EPPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000)),
                ('publication_date', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduplatform_rest_app.epclass')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eduplatform_rest_app.eptask')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eduplatform_rest_app.epunit')),
            ],
        ),
        migrations.CreateModel(
            name='EPPostDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduplatform_rest_app.epdocument')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduplatform_rest_app.eppost')),
            ],
        ),
        migrations.CreateModel(
            name='EPTaskSubmitDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduplatform_rest_app.epdocument')),
                ('task_submit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduplatform_rest_app.eppost')),
            ],
        ),
        migrations.CreateModel(
            name='EPUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('encrypted_password', models.CharField(max_length=120)),
                ('role', models.IntegerField()),
                ('student_group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eduplatform_rest_app.epgroup')),
            ],
        ),
        migrations.CreateModel(
            name='EPTaskSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('submit_date', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduplatform_rest_app.eptask')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduplatform_rest_app.epuser')),
            ],
        ),
        migrations.AddField(
            model_name='epgroup',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eduplatform_rest_app.epuser'),
        ),
        migrations.CreateModel(
            name='EPUserClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduplatform_rest_app.epclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduplatform_rest_app.epuser')),
            ],
        ),
        migrations.CreateModel(
            name='EPUserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduplatform_rest_app.epuser')),
            ],
        ),
    ]
