# Generated by Django 5.1.1 on 2024-11-25 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduplatform_rest_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPUnitClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduplatform_rest_app.epclass')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduplatform_rest_app.epunit')),
            ],
        ),
    ]
