# Generated by Django 5.1.1 on 2024-12-19 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000, null=True)),
                ('submit_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('size', models.IntegerField()),
                ('mime_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('tag', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmitDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_rest_app.assignmentsubmit')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_rest_app.document')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7)),
                ('archived', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_rest_app.group')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('content', models.CharField(max_length=2000)),
                ('kind', models.IntegerField()),
                ('publication_date', models.DateTimeField(auto_now=True)),
                ('task_due_date', models.DateField(null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_rest_app.class')),
            ],
        ),
        migrations.AddField(
            model_name='assignmentsubmit',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_rest_app.post'),
        ),
        migrations.CreateModel(
            name='PostDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_rest_app.document')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_rest_app.post')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_rest_app.class')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edu_rest_app.unit'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('encrypted_password', models.CharField(max_length=120)),
                ('role', models.IntegerField()),
                ('student_group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu_rest_app.group')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_rest_app.user'),
        ),
        migrations.AddField(
            model_name='group',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu_rest_app.user'),
        ),
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_rest_app.user'),
        ),
        migrations.AddField(
            model_name='assignmentsubmit',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_rest_app.user'),
        ),
        migrations.CreateModel(
            name='UserClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_rest_app.class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_rest_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50, unique=True)),
                ('one_time_token', models.CharField(max_length=50, unique=True)),
                ('one_time_token_already_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_rest_app.user')),
            ],
        ),
    ]
