# Generated by Django 5.1.1 on 2024-12-30 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_rest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu_rest_app.unit'),
        ),
    ]
