# Generated by Django 5.1.1 on 2024-12-26 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_rest_app', '0002_rename_task_due_date_post_assignment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_amended',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edu_rest_app.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
