# Generated by Django 5.1.1 on 2024-12-14 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_rest_app', '0002_remove_document_url_document_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='edu_rest_app.user'),
            preserve_default=False,
        ),
    ]
