# Generated by Django 5.1.4 on 2025-01-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_rest_app', '0002_alter_post_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folder',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='is_autogenerated',
            field=models.BooleanField(default=False),
        ),
    ]
