# Generated by Django 5.1.1 on 2024-12-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_rest_app', '0003_post_post_amended_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdocument',
            name='amend_removed',
            field=models.BooleanField(default=False),
        ),
    ]
