# Generated by Django 5.1.1 on 2024-12-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_rest_app', '0004_postdocument_amend_removed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_amended',
            new_name='amend_original_post',
        ),
        migrations.RemoveField(
            model_name='postdocument',
            name='amend_removed',
        ),
        migrations.AddField(
            model_name='post',
            name='amend_changes_documents',
            field=models.BooleanField(default=False),
        ),
    ]
