# Generated by Django 5.1.1 on 2024-12-27 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_rest_app', '0005_rename_post_amended_post_amend_original_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='amend_changes_documents',
            new_name='amendment_changes_documents',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='amend_original_post',
            new_name='amendment_original_post',
        ),
    ]
