# Generated by Django 5.1.1 on 2024-12-28 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_rest_app', '0006_rename_amend_changes_documents_post_amendment_changes_documents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='amendment_changes_documents',
        ),
    ]
