INSERT INTO edu_app_user(id,
                         username,
                         name,
                         surname,
                         encrypted_password,
                         role,
                         student_group_id,
                         max_folders,
                         max_documents,
                         max_documents_size,
                         last_password_change,
                         password_reset_token,
                         archived)
                 VALUES (1,
                         "admin",
                         "admin",
                         "admin",
                         "$2b$12$gH17GrRoRnsAV263uD9x8urF71L8p.eFODszRD0/9.NUTK.lOgzOS",
                         2,
                         NULL,
                         500,
                         2000,
                         21474836480,
                         NULL,
                         NULL,
                         FALSE);