# Generated by Django 5.2.6 on 2026-03-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Student'), (1, 'Teacher'), (2, 'Teacher Sysadmin'), (3, 'Teacher Leader'), (4, 'Teacher Traineeship Coordinator')]),
        ),
    ]
