# Generated by Django 5.1.7 on 2025-07-30 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu_app.user'),
        ),
        migrations.AlterField(
            model_name='class',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edu_app.group'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu_app.user'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu_app.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='edu_app.group'),
        ),
    ]
