# Generated by Django 5.2.6 on 2026-03-17 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('overview', models.CharField(max_length=300)),
                ('cif', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Student'), (1, 'Teacher'), (2, 'Teacher Sysadmin'), (3, 'Teacher Leader'), (4, 'Teacher Traineeship Coordinator')]),
        ),
        migrations.CreateModel(
            name='CompanyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Meeting'), (1, 'Virtual Meeting'), (2, 'Added Contact Details'), (3, 'Interested About Next Traineeship Period'), (4, 'Other')])),
                ('date_time', models.DateTimeField(null=True)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('participants', models.CharField(max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_app.user')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_app.company')),
            ],
        ),
    ]
