# Generated by Django 5.2.6 on 2026-04-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0002_company_alter_user_role_companyevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.IntegerField(choices=[(0, 'Unspecified'), (1, 'Software'), (2, 'Accounting'), (3, 'Both')], default=0),
        ),
    ]
