# Generated by Django 5.1.7 on 2025-07-31 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0002_alter_announcement_author_alter_class_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='mode',
            field=models.IntegerField(choices=[(0, 'Regular'), (1, 'Secret Answers')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='edu_app.folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent_folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='edu_app.folder'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='edu_app.folder'),
        ),
    ]
