# Generated by Django 5.2.6 on 2026-03-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('overview', models.CharField(max_length=300)),
                ('cif', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Meeting'), (1, 'Virtual Meeting'), (2, 'Added Contact Details'), (3, 'Interested About Next Traineeship Period'), (4, 'Other')])),
                ('date_time', models.DateTimeField()),
                ('description', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
