# Generated by Django 5.2.6 on 2026-03-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0003_company_companyevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
