# Generated by Django 5.2.6 on 2026-03-13 11:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0004_company_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyevent',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='edu_app.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
