# Generated by Django 5.2.6 on 2026-03-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0005_companyevent_company_companyevent_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyevent',
            name='participants',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='companyevent',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
