# Generated by Django 5.1.7 on 2025-06-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0006_user_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('client_ip', models.CharField(max_length=128, null=True)),
                ('client_user_agent', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='class',
            name='theme',
            field=models.IntegerField(choices=[(0, 'Blue'), (1, 'Dark Blue'), (2, 'Green'), (3, 'Purple'), (4, 'Brown'), (5, 'Red'), (6, 'Orange'), (7, 'Yellow')]),
        ),
    ]
