# Generated by Django 5.2.6 on 2026-03-13 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0006_companyevent_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyevent',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='edu_app.user'),
            preserve_default=False,
        ),
    ]
