# Generated by Django 5.2.6 on 2026-03-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0007_companyevent_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyevent',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
