# Generated by Django 5.1.7 on 2025-06-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0009_user_last_password_change_usersession_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
