# Generated by Django 5.1.7 on 2025-06-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0010_user_password_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
