# Generated by Django 5.1.7 on 2025-06-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0011_alter_user_password_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_password_change',
            field=models.DateTimeField(null=True),
        ),
    ]
