# Generated by Django 5.1.7 on 2025-07-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0012_alter_user_last_password_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='assignment_due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
