# Generated by Django 5.1.7 on 2025-07-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0014_alter_post_assignment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='assignment_due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
