# Generated by Django 5.1.7 on 2025-07-09 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0016_remove_folder_is_autogenerated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicesQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('number', models.IntegerField()),
                ('correct_answer_score', models.FloatField(null=True)),
                ('incorrect_answer_score', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChoicesQuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_app.choicesquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ChoicesQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_app.user')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_app.choicesquestionchoice')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('archived', models.BooleanField(default=False)),
                ('is_protected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_app.user')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edu_app.folder')),
            ],
        ),
        migrations.CreateModel(
            name='PostQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_app.post')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_app.questionnaire')),
            ],
        ),
        migrations.AddField(
            model_name='choicesquestion',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_app.questionnaire'),
        ),
        migrations.CreateModel(
            name='AnnouncementQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_app.announcement')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_app.questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('number', models.IntegerField()),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_app.questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='TextQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_app.user')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_app.textquestion')),
            ],
        ),
    ]
