# Generated by Django 5.1.7 on 2025-07-15 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0017_choicesquestion_choicesquestionchoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicesquestionanswer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='choicesquestionanswer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='textquestionanswer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='textquestionanswer',
            name='created_at',
        ),
        migrations.CreateModel(
            name='QuestionnaireSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_app.questionnaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='choicesquestionanswer',
            name='submit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='edu_app.questionnairesubmit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textquestionanswer',
            name='submit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='edu_app.questionnairesubmit'),
            preserve_default=False,
        ),
    ]
