# Generated by Django 5.1.7 on 2025-07-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0018_remove_choicesquestionanswer_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicesquestionchoice',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
