# Generated by Django 5.1.7 on 2025-07-16 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0019_choicesquestionchoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestionnairePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_app.questionnaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_app.user')),
            ],
        ),
    ]
