# Generated by Django 5.1.7 on 2025-07-16 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0020_userquestionnairepermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_protected',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='is_protected',
        ),
    ]
