# Generated by Django 5.1.7 on 2025-07-16 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0021_remove_document_is_protected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementdocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edu_app.document'),
        ),
        migrations.AlterField(
            model_name='announcementquestionnaire',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edu_app.questionnaire'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmitdocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edu_app.document'),
        ),
        migrations.AlterField(
            model_name='postdocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edu_app.document'),
        ),
        migrations.AlterField(
            model_name='postquestionnaire',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edu_app.questionnaire'),
        ),
    ]
