# Generated by Django 5.1.7 on 2025-07-17 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0022_alter_announcementdocument_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnairesubmit',
            old_name='user',
            new_name='author',
        ),
    ]
