# Generated by Django 5.1.7 on 2025-07-18 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0023_rename_user_questionnairesubmit_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmit',
            name='questionnaire_submit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edu_app.questionnairesubmit'),
        ),
    ]
