"""
Django settings for eduplatform_rest project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR_PARENT = BASE_DIR.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v!9@@keqi6##cx8y8bgomwfyvvnf2lgayct5m0nkx&rfuk*^*e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# https://docs.djangoproject.com/en/5.2/ref/settings/#data-upload-max-memory-size
# Defaults to 2.5Mb (2.5 * 1024 * 1024)
# Here we reduce it to 20Kb (20 * 1024) because the larger expected POST data
# is 3000 characters + a few more small fields, so even using UTF8 4 byte chars,
# that would be ~3500 * 4 ~= 14000 bytes. 20Kb is safe enough and (I believe)
# makes the server more robust against maliciously large request bodies.

DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 # 20 Kb

INSTALLED_APPS = [
    'edu_app.apps.EduAppConfig'
]

MIDDLEWARE = [
    'edu_app.middleware_cors.CORSMiddleware',
    'edu_app.middleware_auth.AuthMiddleware',
]

ROOT_URLCONF = 'edu_rest_public.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'edu_rest_public.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR_PARENT / 'database' / 'db.sqlite3',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

