from django.urls import path
from .preconditions import facade

urlpatterns = [
    path("admin/home",                          facade.admin_home),
    path("admin/users",                         facade.admin_create_user),
    path("admin/users/<username>",              facade.admin_edit_delete_user),
    path("admin/teachers",                      facade.admin_get_teachers),
    path("admin/groups",                        facade.admin_create_group),
    path("admin/classes",                       facade.admin_get_classes),
    path("users",                               facade.users_search),
    path("sessions",                            facade.users_login_logout),
    path("passwords",                           facade.users_reset_password),
    path("groups",                              facade.groups_get_all),
    path("groups/<group_tag>/announcements",    facade.groups_create_get_announcements),
    path("announcements/<int:a_id>",            facade.groups_edit_delete_announcement),
    path("classes",                             facade.classes_create_get_my_classes),
    path("classes/<int:c_id>",                  facade.classes_get_edit_delete_class),
    path("classes/<int:c_id>/users",            facade.classes_get_add_participants),
    path("classes/<int:c_id>/users/<username>", facade.classes_delete_participant),
    path("classes/<int:c_id>/units",            facade.classes_create_unit),
    path("units/<int:u_id>",                    facade.classes_edit_delete_unit),
    path("classes/<int:c_id>/scores",           facade.classes_download_scores),
    path("classes/<int:c_id>/posts",            facade.posts_create),
    path("posts/<int:p_id>/amendments",         facade.posts_amend),
    path("assignments/<int:a_id>",              facade.posts_get_assignment),
    path("assignments/<int:a_id>/submits",      facade.posts_create_assignment_submit),
    path("assignments/<int:a_id>/submits/<username>/score", facade.posts_create_delete_score),
    path("assignments/<int:a_id>/scores",       facade.posts_publish_all_scores),
    path("documents",                           facade.documents_get_my_files),
    path("folders",                             facade.documents_create_folder),
    path("files/permissions",                   facade.documents_update_files_permissions),
    path("documents/<d_id>",                    facade.documents_move_document),
    path("documents/<d_id>/users",              facade.documents_get_document_users),
    path("folders/<int:f_id>",                  facade.documents_move_folder),
    path("folders/<int:f_id>/users",            facade.documents_get_folder_users),
    path("questionnaires/<int:q_id>",           facade.documents_move_or_delete_questionnaire),
    path("questionnaires/<int:q_id>/users",     facade.documents_get_questionnaire_users),
    path("questionnaires",                      facade.questionnaires_create),
    path("questionnaires/<int:q_id>/questions", facade.questionnaires_get_questions),
    path("questionnaires/<int:q_id>/results",   facade.questionnaires_get_results),
    path("questionnaires/<int:q_id>/submits",   facade.questionnaires_create_submit),
    path("questionnaires/<int:q_id>/submits/<username>", facade.questionnaires_get_submit),
]
