# Generated by Django 4.2.6 on 2024-06-10 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EPClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EPGroup',
            fields=[
                ('tag', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EPUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('encrypted_password', models.CharField(max_length=120)),
                ('is_teacher', models.BooleanField(default=False)),
                ('is_school_leader', models.BooleanField(default=False)),
                ('is_sysadmin', models.BooleanField(default=False)),
                ('student_registered_group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eduplatform_rest_app.epgroup')),
            ],
        ),
        migrations.CreateModel(
            name='EPUserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduplatform_rest_app.epuser')),
            ],
        ),
        migrations.CreateModel(
            name='EPUserClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduplatform_rest_app.epclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduplatform_rest_app.epuser')),
            ],
        ),
        migrations.AddField(
            model_name='epgroup',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduplatform_rest_app.epuser'),
        ),
        migrations.AddField(
            model_name='epclass',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduplatform_rest_app.epgroup'),
        ),
    ]
