# Generated by Django 5.1.1 on 2024-10-20 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduplatform_rest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epuser',
            name='student_group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eduplatform_rest_app.epgroup'),
        ),
    ]
