# Generated by Django 5.1.1 on 2024-10-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduplatform_rest_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epclass',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
