# Generated by Django 5.1.1 on 2024-11-25 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduplatform_rest_app', '0003_epunit_classroom_delete_epunitclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eptasksubmit',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduplatform_rest_app.eppost'),
        ),
        migrations.RemoveField(
            model_name='eppost',
            name='task',
        ),
        migrations.AddField(
            model_name='eppost',
            name='task_due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='eppost',
            name='task_instructions',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='eppost',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='EPTask',
        ),
    ]
