# Generated by Django 5.1.1 on 2024-11-26 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduplatform_rest_app', '0004_alter_eptasksubmit_task_remove_eppost_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eppost',
            name='task_instructions',
        ),
    ]
