# Generated by Django 5.1.1 on 2024-12-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduplatform_rest_app', '0005_remove_eppost_task_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='eppost',
            name='kind',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
