# Generated by Django 5.1.1 on 2024-12-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduplatform_rest_app', '0006_eppost_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eppost',
            name='task_due_date',
            field=models.DateField(null=True),
        ),
    ]
